---
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - {import_role: name=root_userapps tasks_from=base, tags: ['base']}
    - {import_role: name=root_userapps tasks_from=devtools, tags: ['devtools']}
    - {import_role: name=root_userapps tasks_from=podman, tags: ['podman']}
    - {import_role: name=root_userapps tasks_from=steam, tags: ['steam']}
