- name: photo > Install photo management softwares
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - exiv2
      - imagemagick
      - perl-image-exiftool
      - rawtherapee
      - shotwell

- name: photo > Install FastPhotoTagger dependencies
  community.general.pacman: name=jre11-openjdk
