- name: desktop-files > Copy "NoDisplay" desktop files
  ansible.builtin.copy: src=nodisplay.desktop dest=~/.local/share/applications/{{ item }}.desktop mode=0400
  loop:
    - avahi-discover
    - bssh
    - bvnc
    - cmake-gui
    - electron11
    - electron
    - gtk-lshw
    - io.github.quodlibet.ExFalso
    - jconsole-java11-openjdk
    - jshell-java11-openjdk
    - vim

- name: desktop-files > Copy custom desktop files
  ansible.builtin.copy: src={{ item }} dest=~/.local/share/applications mode=0400
  with_fileglob: 'desktop_files/*.desktop'
