- name: dotfiles > Create symlinks for dotfiles
  ansible.builtin.file: src="{{ item.src }}" dest="~/.{{ item.path }}" state=link force=yes
  with_community.general.filetree: dotfiles/
  when: item.state == 'file'
